#### Tensorflow Atividade

<img src='images/iris.jpg' width= 500px>

No conjunto de dados íris, queremos classificar as flores em 3 tipos de espécie diferente:

    0 = 'setosa'
    1 = 'versicolor'
    2 = 'virginica'


Use a biblioteca Tensorflow, com ajuda da API Keras para treinar uma rede neural para fazer essa classificação.


Dica: Como cada flor contém 4 características use o **input_shape= (4,)**



#### Bibliotecas

In [2]:
# %pip install tensorflow
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score


#### Importando o Dataset

In [3]:
# importando dataset
dataset = pd.read_csv("iris.csv")
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

#### Separando o alvo e os dados para treino e teste

In [4]:
# extraindo características (x)
x = np.array(dataset.loc[:, ["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)"]])

# extraindo resultado
d = np.array(dataset.loc[:,"target"])

# Embaralhando os dados
shuffle = np.random.permutation(len(x))
x = x[shuffle]
d = d[shuffle]

# Separando dados de treino (80%) e teste (20%)
limite = int(len(x) * 0.8)

x_treino = x[0:limite]
x_teste = x[limite: ]

d_treino = d[0:limite]
d_teste = d[limite: ]

#### Configurando a rede, compilação e treino

In [5]:
# Configurando a rede neural
model = keras.Sequential([
    keras.layers.Dense(8, activation='sigmoid', input_shape=(4,)),  # Ajuste da input_shape
    keras.layers.Dense(5, activation='sigmoid'),
    keras.layers.Dense(3, activation='softmax')
])

# Compilando a rede neural
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Treinando a rede neural
model.fit(x_treino, d_treino, epochs=1000)

Epoch 1/1000


c:\Users\mathe\anaconda3\envs\OCR\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3287 - loss: 1.4747
Epoch 2/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3517 - loss: 1.3737 
Epoch 3/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.3642 - loss: 1.3853  
Epoch 4/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.3215 - loss: 1.4343
Epoch 5/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3735 - loss: 1.3113 
Epoch 6/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3204 - loss: 1.3726 
Epoch 7/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3235 - loss: 1.3728 
Epoch 8/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.3287 - loss: 1.3546  
Epoch 9/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3319 - loss: 1.3233 
Epoch 10/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3787 - loss: 1.2580 
Epoch 11/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3704 - loss: 1.2739 
Epoch 12/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3579 - loss

#### Predição do modelo

In [6]:
previsao = model.predict(x_teste)
print(previsao)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
[[1.9338461e-02 9.7050101e-01 1.0160492e-02]
 [7.0344773e-04 6.1475340e-02 9.3782121e-01]
 [9.8260123e-01 1.6533701e-02 8.6505892e-04]
 [2.8722188e-02 9.6266800e-01 8.6097717e-03]
 [2.2404691e-02 9.6879780e-01 8.7975133e-03]
 [1.6751156e-04 1.5090196e-02 9.8474228e-01]
 [9.8153198e-01 1.7563617e-02 9.0441754e-04]
 [9.8227870e-01 1.6844349e-02 8.7698660e-04]
 [2.2208941e-04 1.9859912e-02 9.7991806e-01]
 [9.8197985e-01 1.7132180e-02 8.8802131e-04]
 [9.8080176e-01 1.8267313e-02 9.3090755e-04]
 [9.7696334e-01 2.1970792e-02 1.0658395e-03]
 [5.2023856e-03 4.3074647e-01 5.6405115e-01]
 [1.5942298e-04 1.4368868e-02 9.8547167e-01]
 [2.0162228e-02 9.7049451e-01 9.3433019e-03]
 [1.5698189e-02 9.7021413e-01 1.4087657e-02]
 [8.2065474e-04 7.1526177e-02 9.2765313e-01]
 [9.8027843e-01 1.8771837e-02 9.4974920e-04]
 [1.1854841e-02 8.9790785e-01 9.0237342e-02]
 [9.8167586e-01 1.7424880e-02 8.9918921e-04]
 [9.8273176e-01 1.6408041e-02 8.6023734e-04]
 [1.3434808e-04 1

#### Visão do erro e precisão do modelo

In [7]:
# Convertendo as probabilidades nas classes previstas
previsoes = np.argmax(previsao, axis=1)

# Exibindo as previsões
print("Previsões: ", previsoes)
print("Valores reais: ", d_teste)

# Calculando e exibindo a precisão
accuracy = accuracy_score(d_teste, previsoes)
print("Acurácia: ", accuracy)

# Exibindo a matriz de confusão
conf_matrix = confusion_matrix(d_teste, previsoes)
print("Matriz de confusão:\n", conf_matrix)

# Exibindo o relatório de classificação (precisão, recall, F1-score)
class_report = classification_report(d_teste, previsoes)
print("Relatório de classificação:\n", class_report)

Previsões:  [1 2 0 1 1 2 0 0 2 0 0 0 2 2 1 1 2 0 1 0 0 2 1 1 1 2 0 0 1 1]
Valores reais:  [1 2 0 1 1 2 0 0 2 0 0 0 1 2 1 1 2 0 1 0 0 2 1 1 1 2 0 0 1 1]
Acurácia:  0.9666666666666667
Matriz de confusão:
 [[11  0  0]
 [ 0 11  1]
 [ 0  0  7]]
Relatório de classificação:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        12
           2       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

